title: Whmcs-responsive-email-templates
description: WHMCS Responsive Email Templates
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
  - algoliasearch-jekyll
  
  algolia:
  application_id: 'BW98CBKN8O'
  index_name:     'whmcs-email-theme'
  
  port: 4009
  
  exclude:
  - out
  - _site
  - _drafts
  - configs/
  - vendor
  
